# Sửa lại bộ nhớ JVM cho chuẩn, tránh khai báo MaxMetaspaceSize 2 lần
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

# TẮT Incremental Compilation để tránh lỗi Different Roots (C:\ vs D:\)
kotlin.incremental=false
kotlin.incremental.java=false